[package]
name = "piro/untitled"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"

[server-dependencies]
cmdr = "evaera/cmdr@1.12.0"
profilestore = "lm-loleris/profilestore@1.0.3"
